---
- name: Install Java
  ansible.builtin.dnf:
    name: java-17-amazon-corretto
    state: present

- name: Install Tomcat
  ansible.builtin.dnf:
    name: tomcat
    state: present

- name: Download vprofile application WAR file from S3
  amazon.aws.s3_object:
    bucket: vprofile-artifacts-747336059892
    object: app/vprofile-v2.war
    dest: /opt/tomcat/webapps/vprofile.war
    mode: get
  notify: Restart Tomcat

- name: Start and enable Tomcat service
  ansible.builtin.service:
    name: tomcat
    state: started
    enabled: true
