all:
  children:
    app:
      hosts:
        tomcat01:
          ansible_host: i-07cdc61e6b1142ec5
    db:
      hosts:
        mariadb01:
          ansible_host: i-0fe7a3a6b6a2f0370
    cache:
      hosts:
        memcached01:
          ansible_host: i-02b3dc69a55f16042
    mq:
      hosts:
        rabbitmq01:
          ansible_host: i-069441e9930abc795
  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_region: us-east-1
    ansible_aws_ssm_bucket_name: vprofile-ansible-ssm-1790055238
