all:
  children:
    app:
      hosts:
        tomcat01:
          ansible_host: i-07cd82896ef307617
    db:
      hosts:
        mariadb01:
          ansible_host: i-00fad7b130b62fb64
    cache:
      hosts:
        memcached01:
          ansible_host: i-0adafe2d23aa927fa
    mq:
      hosts:
        rabbitmq01:
          ansible_host: i-0e3142d8be4ef6eee
  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_region: us-east-1
    ansible_aws_ssm_bucket_name: vprofile-ansible-ssm-1790055238
